In [143]:
import numpy as np
from scipy import io, integrate, linalg, signal
from scipy.sparse.linalg import cg, eigs

a = np.array((1,1,23,21,23,123,12))

In [5]:
np.ndim(a)

1

In [8]:
np.size(a)

7

In [9]:
a.shape

(7,)

In [10]:
np.block([[a,a],[a,a]])

array([[  1,   1,  23,  21,  23, 123,  12,   1,   1,  23,  21,  23, 123,
         12],
       [  1,   1,  23,  21,  23, 123,  12,   1,   1,  23,  21,  23, 123,
         12]])

In [11]:
a[-1]

12

In [28]:
B = np.array((1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16)).reshape((4,4))
B

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [29]:
B[1,1]

6

In [26]:
B[-3:]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [27]:
B[0:3,1:2]

array([[ 2],
       [ 6],
       [10]])

In [31]:
B[np.ix_([1,2,3],[0,2])]

array([[ 5,  7],
       [ 9, 11],
       [13, 15]])

In [33]:
C = np.random.rand(21,21)

In [34]:
C[2:21:2,:]

array([[0.50795545, 0.48936508, 0.54067876, 0.3877504 , 0.80515658,
        0.09005673, 0.7860626 , 0.78982655, 0.06836634, 0.07917667,
        0.54096591, 0.63693553, 0.11297633, 0.22294527, 0.68505408,
        0.03129167, 0.64712718, 0.65773018, 0.04004832, 0.19742811,
        0.66979499],
       [0.36540886, 0.85378718, 0.33451775, 0.70047621, 0.86586032,
        0.94262554, 0.17621397, 0.13278768, 0.27242085, 0.63859063,
        0.69569402, 0.59574855, 0.11666465, 0.39917953, 0.92778887,
        0.24767024, 0.89866584, 0.53402894, 0.44943926, 0.12791323,
        0.04244098],
       [0.3156326 , 0.25628462, 0.57912897, 0.2885751 , 0.72893306,
        0.7482645 , 0.12890675, 0.76897558, 0.644847  , 0.17760294,
        0.615192  , 0.23460024, 0.54182636, 0.24070467, 0.41319899,
        0.25978578, 0.22849712, 0.06512782, 0.80682495, 0.54597361,
        0.75766397],
       [0.04832052, 0.43765049, 0.31369769, 0.53767639, 0.67677963,
        0.00610449, 0.15507278, 0.1168632 , 0.1208702

In [35]:
C[::2,:]

array([[0.66765167, 0.70327315, 0.71019957, 0.61384896, 0.07877105,
        0.0948342 , 0.38565003, 0.93872098, 0.10146884, 0.535532  ,
        0.8972091 , 0.13652558, 0.84987938, 0.26354035, 0.37128465,
        0.08154511, 0.60327041, 0.88705769, 0.16169807, 0.58512215,
        0.04572998],
       [0.50795545, 0.48936508, 0.54067876, 0.3877504 , 0.80515658,
        0.09005673, 0.7860626 , 0.78982655, 0.06836634, 0.07917667,
        0.54096591, 0.63693553, 0.11297633, 0.22294527, 0.68505408,
        0.03129167, 0.64712718, 0.65773018, 0.04004832, 0.19742811,
        0.66979499],
       [0.36540886, 0.85378718, 0.33451775, 0.70047621, 0.86586032,
        0.94262554, 0.17621397, 0.13278768, 0.27242085, 0.63859063,
        0.69569402, 0.59574855, 0.11666465, 0.39917953, 0.92778887,
        0.24767024, 0.89866584, 0.53402894, 0.44943926, 0.12791323,
        0.04244098],
       [0.3156326 , 0.25628462, 0.57912897, 0.2885751 , 0.72893306,
        0.7482645 , 0.12890675, 0.76897558, 0.644847 

In [36]:
B[np.r_[:len(B),0]]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [ 1,  2,  3,  4]])

In [37]:
B.transpose()

array([[ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15],
       [ 4,  8, 12, 16]])

In [38]:
B.conj().T

array([[ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15],
       [ 4,  8, 12, 16]])

In [40]:
B @ B

array([[ 90, 100, 110, 120],
       [202, 228, 254, 280],
       [314, 356, 398, 440],
       [426, 484, 542, 600]])

In [41]:
B * B

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144],
       [169, 196, 225, 256]])

In [42]:
B / B

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [43]:
B **3

array([[   1,    8,   27,   64],
       [ 125,  216,  343,  512],
       [ 729, 1000, 1331, 1728],
       [2197, 2744, 3375, 4096]], dtype=int32)

In [45]:
(B > 4)

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [46]:
np.nonzero(B > 4)

(array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3], dtype=int64),
 array([0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3], dtype=int64))

In [47]:
C[:, np.nonzero(a > 8)[0]]

array([[0.71019957, 0.61384896, 0.07877105, 0.0948342 , 0.38565003],
       [0.99964595, 0.83588417, 0.73720922, 0.36751443, 0.95219909],
       [0.54067876, 0.3877504 , 0.80515658, 0.09005673, 0.7860626 ],
       [0.49694401, 0.73623091, 0.33167801, 0.56177818, 0.4154183 ],
       [0.33451775, 0.70047621, 0.86586032, 0.94262554, 0.17621397],
       [0.68216186, 0.87984085, 0.87529541, 0.72252974, 0.94559731],
       [0.57912897, 0.2885751 , 0.72893306, 0.7482645 , 0.12890675],
       [0.38643026, 0.6155913 , 0.27644926, 0.69047203, 0.5766595 ],
       [0.31369769, 0.53767639, 0.67677963, 0.00610449, 0.15507278],
       [0.06468991, 0.97739081, 0.34953018, 0.66689364, 0.5662745 ],
       [0.98573892, 0.53340685, 0.46022071, 0.80362839, 0.44997946],
       [0.19539218, 0.95886336, 0.18287204, 0.9723965 , 0.2306296 ],
       [0.56900485, 0.83573219, 0.80576633, 0.06502091, 0.13705673],
       [0.33839171, 0.77048957, 0.66956242, 0.81707666, 0.73450392],
       [0.51885701, 0.16234459, 0.

In [50]:
C[:, C[:,0].T > 0.5]

array([[0.66765167, 0.71019957, 0.93872098, 0.13652558, 0.60327041,
        0.16169807],
       [0.01974482, 0.99964595, 0.62909784, 0.49422326, 0.30861164,
        0.33333274],
       [0.50795545, 0.54067876, 0.78982655, 0.63693553, 0.64712718,
        0.04004832],
       [0.42763192, 0.49694401, 0.11997263, 0.83028259, 0.72595403,
        0.87682461],
       [0.36540886, 0.33451775, 0.13278768, 0.59574855, 0.89866584,
        0.44943926],
       [0.18569337, 0.68216186, 0.24469452, 0.17996015, 0.46018781,
        0.3036383 ],
       [0.3156326 , 0.57912897, 0.76897558, 0.23460024, 0.22849712,
        0.80682495],
       [0.85058719, 0.38643026, 0.95571536, 0.51630769, 0.09872904,
        0.87184936],
       [0.04832052, 0.31369769, 0.1168632 , 0.35936763, 0.38455403,
        0.52788009],
       [0.28662007, 0.06468991, 0.7311157 , 0.7281835 , 0.78800516,
        0.28118054],
       [0.25932408, 0.98573892, 0.44523415, 0.39027295, 0.6137215 ,
        0.06465765],
       [0.81778012, 0

In [51]:
C*(C[:,0].T > 0.5)

array([[0.66765167, 0.        , 0.71019957, 0.        , 0.        ,
        0.        , 0.        , 0.93872098, 0.        , 0.        ,
        0.        , 0.13652558, 0.        , 0.        , 0.        ,
        0.        , 0.60327041, 0.        , 0.16169807, 0.        ,
        0.        ],
       [0.01974482, 0.        , 0.99964595, 0.        , 0.        ,
        0.        , 0.        , 0.62909784, 0.        , 0.        ,
        0.        , 0.49422326, 0.        , 0.        , 0.        ,
        0.        , 0.30861164, 0.        , 0.33333274, 0.        ,
        0.        ],
       [0.50795545, 0.        , 0.54067876, 0.        , 0.        ,
        0.        , 0.        , 0.78982655, 0.        , 0.        ,
        0.        , 0.63693553, 0.        , 0.        , 0.        ,
        0.        , 0.64712718, 0.        , 0.04004832, 0.        ,
        0.        ],
       [0.42763192, 0.        , 0.49694401, 0.        , 0.        ,
        0.        , 0.        , 0.11997263, 0.       

In [53]:
G = C.copy()
G[:] = 3
G

array([[3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
        3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
        3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
        3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
        3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
        3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
        3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
        3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
        3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
        3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
        3., 3., 3.,

In [55]:
C[1,:].copy()


array([0.01974482, 0.64398191, 0.99964595, 0.83588417, 0.73720922,
       0.36751443, 0.95219909, 0.62909784, 0.55998114, 0.47259722,
       0.42441957, 0.49422326, 0.44192151, 0.92646357, 0.8736134 ,
       0.48038851, 0.30861164, 0.58253552, 0.33333274, 0.42675823,
       0.59618863])

In [56]:
C.flatten()

array([0.66765167, 0.70327315, 0.71019957, 0.61384896, 0.07877105,
       0.0948342 , 0.38565003, 0.93872098, 0.10146884, 0.535532  ,
       0.8972091 , 0.13652558, 0.84987938, 0.26354035, 0.37128465,
       0.08154511, 0.60327041, 0.88705769, 0.16169807, 0.58512215,
       0.04572998, 0.01974482, 0.64398191, 0.99964595, 0.83588417,
       0.73720922, 0.36751443, 0.95219909, 0.62909784, 0.55998114,
       0.47259722, 0.42441957, 0.49422326, 0.44192151, 0.92646357,
       0.8736134 , 0.48038851, 0.30861164, 0.58253552, 0.33333274,
       0.42675823, 0.59618863, 0.50795545, 0.48936508, 0.54067876,
       0.3877504 , 0.80515658, 0.09005673, 0.7860626 , 0.78982655,
       0.06836634, 0.07917667, 0.54096591, 0.63693553, 0.11297633,
       0.22294527, 0.68505408, 0.03129167, 0.64712718, 0.65773018,
       0.04004832, 0.19742811, 0.66979499, 0.42763192, 0.8077131 ,
       0.49694401, 0.73623091, 0.33167801, 0.56177818, 0.4154183 ,
       0.11997263, 0.32594569, 0.3462954 , 0.09437829, 0.83028

In [58]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [59]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
np.arange(1,11)[:, np.newaxis]

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [61]:
np.zeros((3,4,5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [62]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [63]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [64]:
np.diag(a)

array([[  1,   0,   0,   0,   0,   0,   0],
       [  0,   1,   0,   0,   0,   0,   0],
       [  0,   0,  23,   0,   0,   0,   0],
       [  0,   0,   0,  21,   0,   0,   0],
       [  0,   0,   0,   0,  23,   0,   0],
       [  0,   0,   0,   0,   0, 123,   0],
       [  0,   0,   0,   0,   0,   0,  12]])

In [66]:
np.diag(a,1)

array([[  0,   1,   0,   0,   0,   0,   0,   0],
       [  0,   0,   1,   0,   0,   0,   0,   0],
       [  0,   0,   0,  23,   0,   0,   0,   0],
       [  0,   0,   0,   0,  21,   0,   0,   0],
       [  0,   0,   0,   0,   0,  23,   0,   0],
       [  0,   0,   0,   0,   0,   0, 123,   0],
       [  0,   0,   0,   0,   0,   0,   0,  12],
       [  0,   0,   0,   0,   0,   0,   0,   0]])

In [69]:
np.random.rand(2,3)

array([[0.64637182, 0.05697136, 0.76095196],
       [0.98705373, 0.51300603, 0.19795049]])

In [70]:
np.linspace(1,3,4)

array([1.        , 1.66666667, 2.33333333, 3.        ])

In [71]:
np.mgrid[0:9.,0:6.]

array([[[0., 0., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1., 1.],
        [2., 2., 2., 2., 2., 2.],
        [3., 3., 3., 3., 3., 3.],
        [4., 4., 4., 4., 4., 4.],
        [5., 5., 5., 5., 5., 5.],
        [6., 6., 6., 6., 6., 6.],
        [7., 7., 7., 7., 7., 7.],
        [8., 8., 8., 8., 8., 8.]],

       [[0., 1., 2., 3., 4., 5.],
        [0., 1., 2., 3., 4., 5.],
        [0., 1., 2., 3., 4., 5.],
        [0., 1., 2., 3., 4., 5.],
        [0., 1., 2., 3., 4., 5.],
        [0., 1., 2., 3., 4., 5.],
        [0., 1., 2., 3., 4., 5.],
        [0., 1., 2., 3., 4., 5.],
        [0., 1., 2., 3., 4., 5.]]])

In [73]:
np.ogrid[0:9.,0:6.]

[array([[0.],
        [1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.]]),
 array([[0., 1., 2., 3., 4., 5.]])]

In [74]:
 np.meshgrid([1,2,4],[2,4,5])

[array([[1, 2, 4],
        [1, 2, 4],
        [1, 2, 4]]),
 array([[2, 2, 2],
        [4, 4, 4],
        [5, 5, 5]])]

In [75]:
np.ix_([1,2,4],[2,4,5])

(array([[1],
        [2],
        [4]]),
 array([[2, 4, 5]]))

In [77]:
np.tile(np.arange(3), (4, 5))

array([[0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2]])

In [83]:
np.concatenate((np.arange(10).reshape(2,5),np.arange(10,20).reshape(2,5)), 1)

array([[ 0,  1,  2,  3,  4, 10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9, 15, 16, 17, 18, 19]])

In [84]:
np.concatenate((np.arange(10),np.arange(10,20)))

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [85]:
a.max()

123

In [86]:
np.maximum(a, a**2)

array([    1,     1,   529,   441,   529, 15129,   144])

In [87]:
np.sqrt(B @ B)

array([[ 9.48683298, 10.        , 10.48808848, 10.95445115],
       [14.2126704 , 15.09966887, 15.93737745, 16.73320053],
       [17.72004515, 18.86796226, 19.94993734, 20.97617696],
       [20.63976744, 22.        , 23.28089345, 24.49489743]])

In [88]:
np.logical_and(C>0.5, C<0.75)

array([[ True,  True,  True,  True, False, False, False, False, False,
         True, False, False, False, False, False, False,  True, False,
        False,  True, False],
       [False,  True, False, False,  True, False, False,  True,  True,
        False, False, False, False, False, False, False, False,  True,
        False, False,  True],
       [ True, False,  True, False, False, False, False, False, False,
        False,  True,  True, False, False,  True, False,  True,  True,
        False, False,  True],
       [False, False, False,  True, False,  True, False, False, False,
        False, False, False, False, False, False, False,  True, False,
        False, False, False],
       [False, False, False,  True, False, False, False, False, False,
         True,  True,  True, False, False, False, False, False,  True,
        False, False, False],
       [False,  True,  True, False, False,  True, False, False, False,
        False,  True, False, False, False,  True, False, False, False

In [90]:
np.logical_or(C < 0.1, C > 0.9)

array([[False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False,  True, False, False,
        False, False,  True],
       [ True, False,  True, False, False, False,  True, False, False,
        False, False, False, False,  True, False, False, False, False,
        False, False, False],
       [False, False, False, False, False,  True, False, False,  True,
         True, False, False, False, False, False,  True, False, False,
         True, False, False],
       [False, False, False, False, False, False, False, False, False,
        False,  True, False, False, False,  True, False, False, False,
        False,  True, False],
       [False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False,  True, False, False, False,
        False, False,  True],
       [False, False, False, False, False, False,  True, False,  True,
        False, False, False, False, False, False, False, False, False

In [95]:
J = np.arange(0,256, dtype='int')
K = np.arange(0,256, dtype='int') + 1

K & J

array([  0,   0,   2,   0,   4,   4,   6,   0,   8,   8,  10,   8,  12,
        12,  14,   0,  16,  16,  18,  16,  20,  20,  22,  16,  24,  24,
        26,  24,  28,  28,  30,   0,  32,  32,  34,  32,  36,  36,  38,
        32,  40,  40,  42,  40,  44,  44,  46,  32,  48,  48,  50,  48,
        52,  52,  54,  48,  56,  56,  58,  56,  60,  60,  62,   0,  64,
        64,  66,  64,  68,  68,  70,  64,  72,  72,  74,  72,  76,  76,
        78,  64,  80,  80,  82,  80,  84,  84,  86,  80,  88,  88,  90,
        88,  92,  92,  94,  64,  96,  96,  98,  96, 100, 100, 102,  96,
       104, 104, 106, 104, 108, 108, 110,  96, 112, 112, 114, 112, 116,
       116, 118, 112, 120, 120, 122, 120, 124, 124, 126,   0, 128, 128,
       130, 128, 132, 132, 134, 128, 136, 136, 138, 136, 140, 140, 142,
       128, 144, 144, 146, 144, 148, 148, 150, 144, 152, 152, 154, 152,
       156, 156, 158, 128, 160, 160, 162, 160, 164, 164, 166, 160, 168,
       168, 170, 168, 172, 172, 174, 160, 176, 176, 178, 176, 18

In [96]:
K | J

array([  1,   3,   3,   7,   5,   7,   7,  15,   9,  11,  11,  15,  13,
        15,  15,  31,  17,  19,  19,  23,  21,  23,  23,  31,  25,  27,
        27,  31,  29,  31,  31,  63,  33,  35,  35,  39,  37,  39,  39,
        47,  41,  43,  43,  47,  45,  47,  47,  63,  49,  51,  51,  55,
        53,  55,  55,  63,  57,  59,  59,  63,  61,  63,  63, 127,  65,
        67,  67,  71,  69,  71,  71,  79,  73,  75,  75,  79,  77,  79,
        79,  95,  81,  83,  83,  87,  85,  87,  87,  95,  89,  91,  91,
        95,  93,  95,  95, 127,  97,  99,  99, 103, 101, 103, 103, 111,
       105, 107, 107, 111, 109, 111, 111, 127, 113, 115, 115, 119, 117,
       119, 119, 127, 121, 123, 123, 127, 125, 127, 127, 255, 129, 131,
       131, 135, 133, 135, 135, 143, 137, 139, 139, 143, 141, 143, 143,
       159, 145, 147, 147, 151, 149, 151, 151, 159, 153, 155, 155, 159,
       157, 159, 159, 191, 161, 163, 163, 167, 165, 167, 167, 175, 169,
       171, 171, 175, 173, 175, 175, 191, 177, 179, 179, 183, 18

In [97]:
np.linalg.inv(C)

array([[-0.26672426, -1.08147473,  1.6819471 , -0.03266171,  0.16098261,
        -0.49944951, -0.31140883,  1.19052311,  0.36627422, -0.98524635,
        -0.02013484,  1.01620187,  0.01110087,  0.43544334,  0.11230539,
         0.22619511,  0.9034426 ,  0.61301652, -1.67652619, -0.08237231,
        -1.32202516],
       [ 0.12292603, -0.38321704,  0.94855221,  0.41142747,  0.90124711,
        -0.67850681, -0.4083396 ,  1.04675666,  0.5158068 , -0.70814768,
        -0.25743684,  0.40006358, -0.58185912,  0.45502567, -0.08797323,
        -0.53857071,  0.84124406,  1.64729373, -2.1421718 ,  0.13604767,
        -1.55460387],
       [ 0.25038896,  0.7603968 ,  0.22614706,  0.03850001, -0.08494815,
        -0.93724537,  0.210459  , -0.42333658,  0.3034296 , -0.77739081,
         0.43836998,  0.40936231, -0.08954172,  0.24984884, -0.34600119,
        -0.16906395, -0.90455167, -0.06034046,  0.51895515,  0.31728564,
         0.34723017],
       [ 0.44480822,  0.92754689, -1.1925983 , -0.10372324

In [101]:
np.linalg.pinv(B)

array([[-0.285 , -0.145 , -0.005 ,  0.135 ],
       [-0.1075, -0.0525,  0.0025,  0.0575],
       [ 0.07  ,  0.04  ,  0.01  , -0.02  ],
       [ 0.2475,  0.1325,  0.0175, -0.0975]])

In [103]:
np.linalg.matrix_rank(B)

2

In [108]:
np.linalg.solve(B, B[2,:])

array([-6.75,  4.25,  3.75, -1.  ])

In [109]:
np.linalg.svd(B)

SVDResult(U=array([[-0.13472212, -0.82574206,  0.38124745, -0.39325613],
       [-0.3407577 , -0.4288172 , -0.21521411,  0.80850658],
       [-0.54679327, -0.03189234, -0.71331411, -0.43724476],
       [-0.75282884,  0.36503251,  0.54728078,  0.02199431]]), S=array([3.86226568e+01, 2.07132307e+00, 7.60977226e-16, 3.86063773e-16]), Vh=array([[-0.4284124 , -0.47437252, -0.52033264, -0.56629275],
       [ 0.71865348,  0.27380781, -0.17103786, -0.61588352],
       [ 0.28255951, -0.72647617,  0.6052738 , -0.16135714],
       [-0.46921223,  0.41500889,  0.57761893, -0.52341558]]))

In [120]:
np.linalg.cholesky(np.array((2,-1,0,-1,2,-1,0,-1,2)).reshape(3,3))

array([[ 1.41421356,  0.        ,  0.        ],
       [-0.70710678,  1.22474487,  0.        ],
       [ 0.        , -0.81649658,  1.15470054]])

In [126]:
D, V = np.linalg.eig(B)
print(D)
print(V)

[ 3.62093727e+01 -2.20937271e+00  2.80575969e-16 -8.29646454e-16]
[[-0.15115432 -0.72704996 -0.01128698 -0.250341  ]
 [-0.34923733 -0.28320876  0.42321091  0.69689908]
 [-0.54732033  0.16063243 -0.81256087 -0.64277516]
 [-0.74540333  0.60447363  0.40063694  0.19621708]]


In [150]:
D, V = linalg.eig(B, np.random.rand(B.shape[0], B.shape[1]))
print(D)
print(V)

[-5.13011045e+01+0.j  1.02614934e+01+0.j  4.69505866e-15+0.j
  1.56664418e-15+0.j]
[[ 0.78126873  0.68870424 -0.36104822  0.42786893]
 [-0.03516474 -0.0116871   0.17440125 -0.82536462]
 [-0.61764839 -0.72494302  0.73434214  0.36712246]
 [ 0.08302458 -0.00273762 -0.54769518  0.03037323]]


In [151]:
D,V = eigs(B, k=3)
print(D)
print(V)

[ 3.62093727e+01+0.j -2.20937271e+00+0.j  2.80575969e-16+0.j
 -8.29646454e-16+0.j]
[[-0.15115432 -0.72704996 -0.01128698 -0.250341  ]
 [-0.34923733 -0.28320876  0.42321091  0.69689908]
 [-0.54732033  0.16063243 -0.81256087 -0.64277516]
 [-0.74540333  0.60447363  0.40063694  0.19621708]]


In [134]:
Q,R = np.linalg.qr(B)
print(Q,R)

[[-0.06019293 -0.83449195 -0.19896747 -0.51030574]
 [-0.30096463 -0.45762462  0.6456494   0.53210606]
 [-0.54173634 -0.08075729 -0.69439639  0.4667051 ]
 [-0.78250805  0.29611005  0.24771446 -0.48850542]] [[-1.66132477e+01 -1.82986497e+01 -1.99840516e+01 -2.16694536e+01]
 [ 0.00000000e+00 -1.07676380e+00 -2.15352761e+00 -3.23029141e+00]
 [ 0.00000000e+00  0.00000000e+00  1.69104133e-15 -2.91558850e-16]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 -1.57441779e-15]]


In [144]:
P,L,U = linalg.lu(B)
print(P)
print(L)
print(U)

[[0. 1. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [1. 0. 0. 0.]]
[[ 1.          0.          0.          0.        ]
 [ 0.07692308  1.          0.          0.        ]
 [ 0.69230769  0.33333333  1.          0.        ]
 [ 0.38461538  0.66666667 -0.5         1.        ]]
[[ 1.30000000e+01  1.40000000e+01  1.50000000e+01  1.60000000e+01]
 [ 0.00000000e+00  9.23076923e-01  1.84615385e+00  2.76923077e+00]
 [ 0.00000000e+00  0.00000000e+00 -1.77635684e-15 -1.77635684e-15]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 -2.22044605e-16]]


In [152]:
cg

<function scipy.sparse.linalg._isolve.iterative.cg(A, b, x0=None, tol=1e-05, maxiter=None, M=None, callback=None, atol=None)>

In [153]:
np.fft.fft(a)

array([ 204.          +0.j        ,  -63.02531912+106.960705j  ,
       -106.00067557 -34.22782984j,   70.52599469 -71.46057129j,
         70.52599469 +71.46057129j, -106.00067557 +34.22782984j,
        -63.02531912-106.960705j  ])

In [154]:
np.fft.ifft(a)

array([ 29.14285714 +0.j        ,  -9.00361702-15.28010071j,
       -15.14295365 +4.88968998j,  10.0751421 +10.20865304j,
        10.0751421 -10.20865304j, -15.14295365 -4.88968998j,
        -9.00361702+15.28010071j])

In [155]:
np.sort(a)

array([  1,   1,  12,  21,  23,  23, 123])

In [156]:
np.sort(B,axis=1)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [158]:
I = np.argsort(B[:,0])
b = B[I,:]
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [160]:
linalg.lstsq(B, np.random.rand(B.shape[0]))

(array([0.00211429, 0.00845879, 0.01480329, 0.02114778]),
 array([], dtype=float64),
 2,
 array([3.86226568e+01, 2.07132307e+00, 7.60977226e-16, 3.86063773e-16]))

In [163]:
signal.resample(a, int(np.ceil(len(a)/2)))

array([-19.1502842 ,  28.86856302,  16.86418387,  89.98896588])

In [164]:
np.unique(a)

array([  1,  12,  21,  23, 123])

In [165]:
a.squeeze()

array([  1,   1,  23,  21,  23, 123,  12])